apiVersion: apps/v1
kind: Deployment
metadata:
  name: runnermqtt5
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      nodeSelector:
        worker: "6"
      hostname: runnermqtt5
      subdomain: benchnet
      containers:
        - env:
            - name: ADD_NODE_TO_SUFFIX
              value: "false"
            - name: DEPLOY_DIR
              value: /app/configs/builtin-test-suites/deployments
            - name: DEVICE_DIR
              value: /app/configs/builtin-test-suites/devices
            - name: DIST_MODE
              value: name
            - name: NODE_BASE
              value: runner5
            - name: RELEASE_COOKIE
              value: ps_bench_cookie
            - name: RUN_TAG
              value: dds_test
            - name: SCENARIO
              value: protocolsuite_smart_city_dds
            - name: SCEN_DIR
              value: /app/configs/builtin-test-suites/testcases
          image: docker.io/library/ps_bench-runner:latest
          imagePullPolicy: Never
          name: runnermqtt5
          volumeMounts:
            - name: shared
              mountPath: /app/out
              subPath: out
            - name: shared
              mountPath: /app/results
              subPath: result
        - name: igmp-keeper
          image: nicolaka/netshoot:latest
          imagePullPolicy: IfNotPresent
          command: ["sh","-lc"]
          args:
            - |
              set -e
              IP=$(ip -4 -o addr show dev eth0 | awk '{print $4}' | cut -d/ -f1)
              echo "[igmp-keeper] iface=$IP group=239.255.0.1"
              term(){ kill $PID 2>/dev/null || true; exit 0; }; trap term TERM INT
              while true; do
                # 不佔用 RTPS 埠（7650/7660），用隨機高埠維持 membership
                socat -u UDP4-RECVFROM:0,ip-add-membership=239.255.0.1:$IP,so-reuseaddr - &
                PID=$!
                sleep 300
                kill $PID 2>/dev/null || true
              done
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: runnermqtt5-shared-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runnermqtt5-shared-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path