apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: emqx
  name: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: emqx
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: emqx
    spec:
      containers:
        - image: emqx/emqx:latest
          livenessProbe:
            exec:
              command:
                - nc -z 127.0.0.1 1883
            failureThreshold: 20
            periodSeconds: 2
            timeoutSeconds: 1
          name: emqx
          ports:
            - containerPort: 1883
              protocol: TCP
      restartPolicy: Always
