apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: runner
  name: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: runner
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: runner
    spec:
      containers:
        - env:
            - name: ADD_NODE_TO_SUFFIX
              value: "true"
            - name: BROKER_HOST
              value: mqtt
            - name: BROKER_PORT
              value: "1883"
            - name: RELEASE_COOKIE
              value: ps_bench_cookie
            - name: RUN_TAG
              value: run1
            - name: SCENARIO
              value: mqtt_multi_node_light
            - name: SELECTED_SCENARIO
              value: mqtt_multi_node_light
          image: docker.io/library/ps_bench-runner:latest
          name: runner
          volumeMounts:
            - mountPath: /app/out
              name: runner-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: runner-cm0
          name: runner-cm0
