apiVersion: apps/v1
kind: Deployment
metadata:
  name: runnermqtt6
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      nodeSelector:
        worker: "7"
      hostname: runnermqtt6
      subdomain: benchnet
      containers:
        - env:
            - name: ADD_NODE_TO_SUFFIX
              value: "false"
            - name: BROKER_HOST
              value: emqx
            - name: BROKER_PORT
              value: "1883"
            - name: DEPLOY_DIR
              value: /app/configs/builtin-test-suites/deployments
            - name: DEVICE_DIR
              value: /app/configs/builtin-test-suites/devices
            - name: DIST_MODE
              value: name
            - name: NODE_BASE
              value: runner6
            - name: RELEASE_COOKIE
              value: ps_bench_cookie
            - name: RUN_TAG
              value: test_run
            - name: SCENARIO
              value: scalabilitysuite_smart_city_mqttv5_10x_8_node
            - name: SCEN_DIR
              value: /app/configs/builtin-test-suites/testcases
          image: docker.io/library/ps_bench-runner:latest
          imagePullPolicy: Never
          name: runnermqtt6
          volumeMounts:
            - name: shared
              mountPath: /app/out
              subPath: out
            - name: shared
              mountPath: /app/results
              subPath: result
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: runnermqtt6-shared-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runnermqtt6-shared-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path